FROM public.ecr.aws/dataminded/spark-k8s-glue:v3.1.2-hadoop-3.3.1
# remember to mount the aws redentials!

WORKDIR /usr/src/app
COPY requirements.txt ./
USER root
RUN pip3 install -r requirements.txt
# USER 185
# COPY data_part_1.json ./ # debugging purposes
COPY ./py_spark/ .
CMD python3 -O script.py